### ISSUE TITLE
Incorporate auto-alignment

### ISSUE THREAD

**Issue by kubawolanin** [kubawolanin/generator-openhab#10]
@ThomDietrich it's a tribute to you! :wink: (Related to https://github.com/openhab/openhabian/issues/188#issuecomment-318032554)

We could provide a flag to optionally disable (or enable?) this feature, e.g.
```
yo openhab --no-alignment
```

Possible implementation:
https://github.com/annsk/vscode-alignment/blob/master/src/extension.ts#L108

**Comment by kubawolanin** [comment]
Closing this since I'm focusing on the [UI-based home builder](https://github.com/openhab/openhab-core/pull/172). This feature is already implemented there.

**Comment by ThomDietrich** [comment]
Nice! Thanks
