### ISSUE TITLE
Generate Items directly in json database (optionally)

### ISSUE THREAD

**Issue by kubawolanin** [kubawolanin/generator-openhab#9]
Per @BClark09 suggestion from here:
https://community.openhab.org/t/openhab-generator-design-your-smart-home-in-no-time/32250/4?u=kubawolanin

**Comment by BClark09** [comment]
To be clear, I think the choice of having either would be great. Not just "instead of" ;)

**Comment by kubawolanin** [comment]
See my comment here:
https://community.openhab.org/t/openhab-generator-design-your-smart-home-in-no-time/32250/11

It looks like it'd be better for everyone to have this feature in a web-based tool.
Closing this one.

**Comment by VandeurenGlenn** [comment]
Hi @kubawolanin I quickly read the comments on openhab, while it would be nice to have as a web tool, I also find it helpful to have a generator like this one, 

I wrote some code yesterday which reads from discovery and add's everything to jsondb itself, without considering floors & rooms, if you want, I can integrate it into your generator.

**Comment by kubawolanin** [comment]
Hey @VandeurenGlenn! Check out HomeBuilder - [Docs](https://www.openhab.org/docs/configuration/homebuilder.html) and [Demo](http://demo.openhab.org:8080/homebuilder/index.html)

[Here](https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.ui.homebuilder) you can find the sources :)

Happy hacking!
